### ISSUE TITLE
PR can't be merged after its fetched

### ISSUE THREAD

**Issue by fazer1929** [jboss-set/cryo#23]
Cryo is unable to merge PR after getting its details 
It throws the following exception - 
```
java.io.IOException: Cannot run program "pr-merge" (in directory "/home/abagrawa/Desktop/RHP/jboss-eap7"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.jboss.set.cryo.process.ExecuteProcess.getProcessResult(ExecuteProcess.java:54)
	at org.jboss.set.cryo.staging.directory.DirectoryOrientedOperationCenter.mergePullRequest(DirectoryOrientedOperationCenter.java:175)
	at org.jboss.set.cryo.process.BisectablePullRequest.merge(BisectablePullRequest.java:188)
	at org.jboss.set.cryo.Cryo.mergeAvailablePullRequests(Cryo.java:497)
	at org.jboss.set.cryo.Cryo.createStorage(Cryo.java:435)
	at org.jboss.set.cryo.Main.main(Main.java:124)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 7 more
```

**The directory is present despite of what the error informs**.

**Comment by fazer1929** [comment]
it can be fixed by having the `pr-merge` script at the /bin directory(it must be available to the `$PATH` variable).
