### ISSUE TITLE
Return non zero code on any failure

### ISSUE THREAD

**Issue by gaol** [jboss-set/cryo#9]
Some times when services that cryo relaying on are refused to service, there will be exceptions like:

```java
Aug 07, 2021 10:55:38 AM org.jboss.set.aphrodite.Aphrodite init
INFO: Initiating Aphrodite ...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Aug 07, 2021 10:55:41 AM org.jboss.set.aphrodite.issue.trackers.jira.JiraIssueTracker logException
SEVERE: java.util.concurrent.ExecutionException: RestClientException{statusCode=Optional.of(503), errorCollections=[]}
Aug 07, 2021 10:55:41 AM org.jboss.set.cryo.Main log
SEVERE: [CRYO][**00:00:00:03:688**]: Failed to initialize aphrodite!
org.jboss.set.aphrodite.spi.AphroditeException: Unable to initiatilise Aphrodite.
Failed to initialize issue tracker: https://issues.redhat.com

	at org.jboss.set.aphrodite.Aphrodite.init(Aphrodite.java:194)
	at org.jboss.set.aphrodite.Aphrodite.<init>(Aphrodite.java:148)
	at org.jboss.set.aphrodite.Aphrodite.instance(Aphrodite.java:96)
	at org.jboss.set.cryo.Cryo.initAphrodite(Cryo.java:248)
	at org.jboss.set.cryo.Cryo.init(Cryo.java:143)
	at org.jboss.set.cryo.Cryo.createStorage(Cryo.java:427)
	at org.jboss.set.cryo.Main.main(Main.java:124)

Aug 07, 2021 10:55:41 AM org.jboss.set.cryo.Main log
WARNING: [CRYO][**00:00:00:03:689**]: Failed to initialize, check previous errors.
```
But `java -jar cryo.jar` returns `0` in this case, which forces CI script to check logs instead of failing at the end of execution.

It is expected to return non zero code to indicate the failure of the bisect checking.

**Comment by baranowb** [comment]
yep. certainly.

**Comment by baranowb** [comment]
Most likely those ops should be broken down a bit. RN too clumped up IMHO.
